### ISSUE TITLE
documentation for other layouts

### ISSUE THREAD

**Issue by jordanskole** [czajkowski/folder-toc#1]
Hey @czajkowski, getting a kick out of this module so far, thanks for making it! It would be cool if you provided a bit more documentation on the different layouts available, if any, as well as how to create/customize layout templates. Thanks!

**Comment by czajkowski** [comment]
Hi @jordanskole! 
I've updated the module a little and added an example showing how to use a custom template. Let me know if this helps.

**Comment by jordanskole** [comment]
Hey @czajkowski this is great thanks!

**Comment by jordanskole** [comment]
Hey @czajkowski, 

when referencing the `templateDir` the file references the module in the `node_modules` directory, instead of the file itself (or even the absolute path value). This implies that we should be modifying the module directory itself, which isn't preferred. 

Any way we could reference a template inside our working project directory?

**Comment by czajkowski** [comment]
Hi @jordanskole 

You are right, my mistake.
I've pushed a fix and updated example.

**Comment by jordanskole** [comment]
@czajkowski no big deal, and thanks! Really digging this utility so far, it is perfect for what I needed.
